apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-fileserver-nfs

spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:               
    path: /database     #Nome do compartilhamento de arquivos(filestore)
    server: 10.58.162.178 #ip do filestore ou do servidor NFS

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-fileserver-nfs
spec:
  storageClassName: "" #A GCP pede que deixe este campo so com aspas em branco
  accessModes:
  accessModes:
    - ReadWriteMany
  volumeName: pv-fileserver-nfs
  resources:
    requests:
      storage: 10Gi
