name: Publish Docker image

on:
  push:
    branches:
      - 'main'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
           
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: backend/
          push: true
          tags: ${{ secrets.USER }}/app-cicd-dio:1.0
    
  deploy_gcp:
    name: Deploy to GCP 
    runs-on: ubuntu-latest
    steps:
      - name: Executa o ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
                    sudo rm -Rf ./k8s-projetogcp-dio/ && sudo git clone https://github.com/andersonluix/k8s-projetogcp-dio.git && cd k8s-projetogcp-dio && sudo chmod +x ./script.sh && ./script.sh